<a href="https://colab.research.google.com/github/Jayz87/pytorchIntro/blob/main/Day1Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.1+cu121


Creating Tensors

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.item()

7

In [4]:
#vector
vector = torch.tensor([7,17])
vector, scalar

(tensor([ 7, 17]), tensor(7))

In [6]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [11]:
#matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix,matrix.ndim,matrix[1],matrix.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 tensor([ 9, 10]),
 torch.Size([2, 2]))

In [14]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR,TENSOR.ndim,TENSOR.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 3,
 torch.Size([1, 3, 3]))

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [26]:
TENSOR2 = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]],[ [4,7,8],[5,6,9],[8,9,6]]])
TENSOR2,TENSOR2.ndim,TENSOR2.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],
 
         [[4, 7, 8],
          [5, 6, 9],
          [8, 9, 6]]]),
 3,
 torch.Size([2, 3, 3]))

In [27]:
TENSOR2[1]

tensor([[4, 7, 8],
        [5, 6, 9],
        [8, 9, 6]])

In [31]:
#create random tensor of size 3,4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2616, 0.7182, 0.2235, 0.6309],
        [0.1022, 0.4084, 0.2387, 0.7163],
        [0.0358, 0.0411, 0.1351, 0.3556]])

In [32]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [33]:
ranTensor = torch.rand(2,4,5)
ranTensor

tensor([[[0.6421, 0.3962, 0.4164, 0.6855, 0.4885],
         [0.4472, 0.4667, 0.2517, 0.6757, 0.8796],
         [0.9267, 0.5553, 0.5565, 0.7757, 0.7885],
         [0.7259, 0.9981, 0.0756, 0.4626, 0.3913]],

        [[0.2022, 0.6634, 0.2209, 0.8497, 0.3837],
         [0.8181, 0.8075, 0.0451, 0.4257, 0.8219],
         [0.7678, 0.4678, 0.1440, 0.0428, 0.3797],
         [0.2369, 0.6778, 0.4016, 0.5317, 0.6683]]])

In [35]:
zeroes = torch.zeros(3,4)
ones =torch.ones(2,3)
zeroes,ones, ones.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [41]:
#creating a range of tensors
# torch.range()
torch.range(0,6)
torch.arange(1,11)
stepRange = torch.arange(start=1,step=100,end=1000)
stepRange

<ipython-input-41-2c21406e6306>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,6)


tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [43]:

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=stepRange) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device